### ISSUE TITLE
Separate calculations from display

### ISSUE THREAD

**Issue by zinsho** [bhnn/hunter-sim#19]
Right now the display code is interspersed with the calculation/simulation code.  I was trying to look at getting it to output as JSON (partially as an experiment and partially to see what it would take to use the simulator as an API with a web SPA frontend) and had to wrap multiple locations with (pseudo) `if output == 'json'` to collect the JSON data and put the current display code in the else block (or vice-versa).

**Comment by bhnn** [comment]
Yeah I'm not a fan of the output code currently, probably the messiest part of the whole sim. What are your thoughts on transforming `res` in `SimulationManager.run(..)` into a dictionary of human-readable keys that can be easily converted into output strings, together with avg and stdev value? Then it could either be passed into a method that constructs a printable output or be returned by `.run(..)` or `.compare_against(..)`. Or did you already have a possible refactoring in mind?

**Comment by zinsho** [comment]
That would definitely work.  All I'd done (and then without thinking about it did a revert of the checkout so lost the change) was add an extra cli flag for output type (defaulting to `pprint` but allowing for `json`) and then each place doing output had it wrap the current output as `if output == 'pprint'` and otherwise collecting it all into an object.

Ended up with something akin to (had to get rid of the extra Hunter object that you extract when printing to avoid issues with objects not outputting properly):

```
{
  builds: [ Hunter1, (Hunter2) ],
  results: [ Result1, (Result2) ],
  stdev: [ StDev1, StDev2 ],
  iterations: int Iterations
}
```

I didn't like having results and stdev being separate but as a first pass it was easier to keep the object matching what the output gave.
