### ISSUE TITLE
Trample is always applied

### ISSUE THREAD

**Issue by Vocabularix** [bhnn/hunter-sim#2]
Borge will always trample whether the build shows 'true' or 'false'.

Attached: Borge build (extension changed to .txt) + most recent log ran with it (one iteration).
[borge1.txt](https://github.com/bhnn/hunter-sim/files/14088234/borge1.txt)
[20240129-193328_borge1.log](https://github.com/bhnn/hunter-sim/files/14088228/20240129-193328_borge1.log)

Proposed fix:
This condition checks for the presence of 'trample' in the dict, not its value.
https://github.com/bhnn/hunter-sim/blob/73c8c8ef9037907b06a2f8c4b8f1b2ab5b1f259f/hunter-sim/sim.py#L426
Changing the condition to 
`if hunter.mods['trample'] and not isinstance(self.enemies[0], Boss):`
fixes it.

**Comment by bhnn** [comment]
Should be fixed now
