### ISSUE TITLE
Borge LL is also applied to boss

### ISSUE THREAD

**Issue by Vocabularix** [bhnn/hunter-sim#3]
Lucky loot procs on boss fights.

https://github.com/bhnn/hunter-sim/blob/73c8c8ef9037907b06a2f8c4b8f1b2ab5b1f259f/hunter-sim/hunters.py#L185-L189

Suppressing the LL on current_stage 100 brings the LPH variance way down, suggesting that it did proc on the boss in the first place.

**Comment by bhnn** [comment]
Fixed now, thanks!
