### ISSUE TITLE
Support for relics 16 and 17

### ISSUE THREAD

**Issue by digitrev** [bhnn/hunter-sim#30]
Relic 16 (long-range artillery crawler) provides a 2% bonus to Borge's attack power per level (additive). I believe that Relic 17 (I've not unlocked it yet) does the same.

**Comment by bhnn** [comment]
They've both been implemented already in the latest release.
https://github.com/bhnn/hunter-sim/blob/5722b08395935fcff78baa1280642abe3733e158/hunter-sim/hunters.py#L539
https://github.com/bhnn/hunter-sim/blob/5722b08395935fcff78baa1280642abe3733e158/hunter-sim/hunters.py#L1087
